#!/bin/bash
#
# chkconfig: 35 90 12
# description: nDeploy Backends init and stop script
#
# Get function from functions library
. /etc/init.d/functions
### main logic ###
case "$1" in
	start)
		/opt/nDeploy/scripts/init_backends.php --action=start
		;;
	stop)
		/opt/nDeploy/scripts/init_backends.php --action=stop
		;;
	restart)
		/opt/nDeploy/scripts/init_backends.php --action=restart
		;;
	reload)
		/opt/nDeploy/scripts/init_backends.php --action=reload
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
exit 0