#!/bin/bash

touch /opt/nDeploy/conf/backends.yaml
/opt/nDeploy/scripts/update_backend.py PROXY apache 8000
touch /opt/nDeploy/conf/profiles.yaml
/opt/nDeploy/scripts/update_profiles.py PROXY 1000.j2 "Proxy to the Apache Backend (default)"
# /opt/nDeploy/scripts/update_profiles.py NODEJS 4001.j2 "A NodeJS application"
# /opt/nDeploy/scripts/update_profiles.py NODEJS 4002.j2 "Ghost Blog"
# /opt/nDeploy/scripts/update_profiles.py RUBY 2001.j2 "Rack or Ruby on Rails"
# /opt/nDeploy/scripts/update_profiles.py PYTHON 3001.j2 "Python WSGI Application"
# /opt/nDeploy/scripts/update_profiles.py PHP 5001.j2 "Wordpress"
# /opt/nDeploy/scripts/update_profiles.py PHP 5002.j2 "Joomla"
# /opt/nDeploy/scripts/update_profiles.py PHP 5003.j2 "Magento"
# /opt/nDeploy/scripts/update_profiles.py PHP 5500.j2 "High Performance Wordpress"
# /opt/nDeploy/scripts/update_profiles.py HHVM_NOBODY 5001.j2 "Wordpress"
# /opt/nDeploy/scripts/update_profiles.py HHVM_NOBODY 5002.j2 "Joomla"
# /opt/nDeploy/scripts/update_profiles.py HHVM_NOBODY 5003.j2 "Magento"
# /opt/nDeploy/scripts/update_profiles.py HHVM_NOBODY 5500.j2 "High Performance Wordpress"

echo -e '\e[93m Adding cpanel hooks \e[0m'
# delete scripts
/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/reload_nginx.sh --category Stats --event RunAll --stage post --manual
/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/runuserstats_hook_post.py --category Stats --event RunUser --stage post --manual
/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/accountcreate_hook_post.pl --category Whostmgr --event Accounts::Create --stage post --manual
/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/accountmodify_hook_pre.py --category Whostmgr --event Accounts::Modify --stage pre --manual
/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/accountmodify_hook_post.py --category Whostmgr --event Accounts::Modify --stage post --manual
/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/accountremove_hook_pre.py --category Whostmgr --event Accounts::Remove --stage pre --manual

/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/cpanel_functions_hook_post.py --category Cpanel --event Api2::SubDomain::addsubdomain --stage post --manual --exectype script --escalateprivs
/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/cpanel_functions_hook_post.py --category Cpanel --event Api2::SubDomain::changedocroot --stage post --manual --exectype script --escalateprivs
/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/cpanel_functions_hook_post.py --category Cpanel --event Api2::SubDomain::delsubdomain --stage post --manual --exectype script --escalateprivs
/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/cpanel_functions_hook_post.py --category Cpanel --event Api2::AddonDomain::addaddondomain --stage post --manual --exectype script --escalateprivs
/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/cpanel_functions_hook_post.py --category Cpanel --event Api2::AddonDomain::deladdondomain --stage post --manual --exectype script --escalateprivs
/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/cpanel_functions_hook_post.py --category Cpanel --event Api1::Park::park --stage post --manual --exectype script --escalateprivs
/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/cpanel_functions_hook_post.py --category Cpanel --event Api1::Park::unpark --stage post --manual --exectype script --escalateprivs
/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/cpanel_functions_hook_post.py --category Cpanel --event UAPI::SSL::delete_ssl --stage post --manual --exectype script --escalateprivs
/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/cpanel_functions_hook_post.py --category Cpanel --event UAPI::SSL::install_ssl --stage post --manual --exectype script --escalateprivs
/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/cpanel_functions_hook_post.py --category Whostmgr --event Accounts::suspendacct --stage post --manual
/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/cpanel_functions_hook_post.py --category Whostmgr --event Accounts::unsuspendacct --stage post --manual
/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/cpanel_functions_hook_post.py --category Whostmgr --event Accounts::SiteIP::set --stage post --manual

/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/cpanel_removesubdom_functions_hook_post.py --category Cpanel --event Api2::SubDomain::delsubdomain --stage post --manual --exectype script --escalateprivs
/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/cpanel_removeaddon_functions_hook_post.py --category Cpanel --event Api2::AddonDomain::deladdondomain --stage post --manual --exectype script --escalateprivs
#/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/reload_watcher.sh --category System --event upcp --stage post --manual
/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/cpanel_suspension_functions_hook_post.py --category Whostmgr --event Accounts::suspendacct --stage post --manual
/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/cpanel_suspension_functions_hook_post.py --category Whostmgr --event Accounts::unsuspendacct --stage post --manual
/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/convertaddon_hook_pre.py --category ConvertAddon --event convert_addon --stage pre --manual
/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/convertaddon_hook_post.py --category ConvertAddon --event convert_addon --stage post --manual

# add scripts
/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/reload_nginx.sh --category Stats --event RunAll --stage post --manual --escalateprivs 1
/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/runuserstats_hook_post.py --category Stats --event RunUser --stage post --manual
/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/accountcreate_hook_post.pl --category Whostmgr --event Accounts::Create --stage post --manual
/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/accountmodify_hook_pre.py --category Whostmgr --event Accounts::Modify --stage pre --manual
/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/accountmodify_hook_post.py --category Whostmgr --event Accounts::Modify --stage post --manual
/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/accountremove_hook_pre.py --category Whostmgr --event Accounts::Remove --stage pre --manual

/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/cpanel_functions_hook_post.py --category Cpanel --event Api2::SubDomain::addsubdomain --stage post --manual --exectype script --escalateprivs
/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/cpanel_functions_hook_post.py --category Cpanel --event Api2::SubDomain::changedocroot --stage post --manual --exectype script --escalateprivs
/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/cpanel_functions_hook_post.py --category Cpanel --event Api2::SubDomain::delsubdomain --stage post --manual --exectype script --escalateprivs
/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/cpanel_functions_hook_post.py --category Cpanel --event Api2::AddonDomain::addaddondomain --stage post --manual --exectype script --escalateprivs
/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/cpanel_functions_hook_post.py --category Cpanel --event Api2::AddonDomain::deladdondomain --stage post --manual --exectype script --escalateprivs
/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/cpanel_functions_hook_post.py --category Cpanel --event Api1::Park::park --stage post --manual --exectype script --escalateprivs
/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/cpanel_functions_hook_post.py --category Cpanel --event Api1::Park::unpark --stage post --manual --exectype script --escalateprivs
/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/cpanel_functions_hook_post.py --category Cpanel --event UAPI::SSL::delete_ssl --stage post --manual --exectype script --escalateprivs
/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/cpanel_functions_hook_post.py --category Cpanel --event UAPI::SSL::install_ssl --stage post --manual --exectype script --escalateprivs
/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/cpanel_functions_hook_post.py --category Whostmgr --event Accounts::suspendacct --stage post --manual
/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/cpanel_functions_hook_post.py --category Whostmgr --event Accounts::unsuspendacct --stage post --manual
/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/cpanel_functions_hook_post.py --category Whostmgr --event Accounts::SiteIP::set --stage post --manual

/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/cpanel_removesubdom_functions_hook_post.py --category Cpanel --event Api2::SubDomain::delsubdomain --stage post --manual --exectype script --escalateprivs
/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/cpanel_removeaddon_functions_hook_post.py --category Cpanel --event Api2::AddonDomain::deladdondomain --stage post --manual --exectype script --escalateprivs
#/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/reload_watcher.sh --category System --event upcp --stage post --manual
/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/cpanel_suspension_functions_hook_post.py --category Whostmgr --event Accounts::suspendacct --stage post --manual
/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/cpanel_suspension_functions_hook_post.py --category Whostmgr --event Accounts::unsuspendacct --stage post --manual
/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/convertaddon_hook_pre.py --category ConvertAddon --event convert_addon --stage pre --manual
/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/convertaddon_hook_post.py --category ConvertAddon --event convert_addon --stage post --manual


[ ! -d /opt/nDeploy/domain-data ] && mkdir /opt/nDeploy/domain-data
[ ! -d /opt/nDeploy/user-data ] && mkdir /opt/nDeploy/user-data

[ ! -L /usr/local/cpanel/base/frontend/paper_lantern/nDeploy_cp ] && ln -s /opt/nDeploy/nDeploy_cp /usr/local/cpanel/base/frontend/paper_lantern/
[ ! -L /usr/local/cpanel/base/frontend/jupiter/nDeploy_cp ] && ln -s /opt/nDeploy/nDeploy_cp /usr/local/cpanel/base/frontend/jupiter/


echo -e '\e[93m Installing nDeploy plugin in cPanel \e[0m'
/usr/local/cpanel/scripts/install_plugin /opt/nDeploy/nDeploy_cp
