#!/bin/bash

if [ -f /etc/csf/csf.pignore ] ; then
	echo -e '\e[93m Setting up CSF firewall to ignore nginx process \e[0m'
	grep -w '/usr/sbin/nginx' /etc/csf/csf.pignore || echo 'exe:/usr/sbin/nginx' >> /etc/csf/csf.pignore
fi

[ ! -d /etc/nginx/sites-enabled ] && mkdir /etc/nginx/sites-enabled
[ ! -d /etc/nginx/ssl ] && mkdir /etc/nginx/ssl

getent group nginx >/dev/null || groupadd -r nginx
getent passwd nginx >/dev/null || useradd -r -g nginx -s /sbin/nologin -d /var/cache/nginx -c "nginx user"  nginx

if [ -d /etc/systemd ]; then
	systemctl preset nginx.service
	systemctl enable nginx.service
else
	chkconfig --level=235 nginx on
fi