#!/bin/bash

touch /opt/nDeploy/conf/backends.yaml
/opt/nDeploy/scripts/update_backend.py PROXY apache 8000
touch /opt/nDeploy/conf/profiles.yaml
/opt/nDeploy/scripts/update_profiles.py PROXY 1000 "Proxy to the Apache Backend (default)"
/opt/nDeploy/scripts/update_profiles.py PROXY 1003 "Redirect to https(SSL)"
/opt/nDeploy/scripts/update_profiles.py NODEJS 4001 "A NodeJS application"
/opt/nDeploy/scripts/update_profiles.py NODEJS 4002 "Ghost Blog"
/opt/nDeploy/scripts/update_profiles.py RUBY 2001 "Rack or Ruby on Rails"
/opt/nDeploy/scripts/update_profiles.py PYTHON 3001 "Python WSGI Application"
/opt/nDeploy/scripts/update_profiles.py PHP 5001 "Wordpress or Drupal"
/opt/nDeploy/scripts/update_profiles.py PHP 5002 "Joomla"
/opt/nDeploy/scripts/update_profiles.py PHP 5003 "Magento"
/opt/nDeploy/scripts/update_profiles.py PHP 5500 "High Performance Wordpress"
/opt/nDeploy/scripts/update_profiles.py HHVM_NOBODY 5001 "Wordpress or Drupal"
/opt/nDeploy/scripts/update_profiles.py HHVM_NOBODY 5002 "Joomla"
/opt/nDeploy/scripts/update_profiles.py HHVM_NOBODY 5003 "Magento"
/opt/nDeploy/scripts/update_profiles.py HHVM_NOBODY 5500 "High Performance Wordpress"

echo -e '\e[93m Adding cpanel hooks \e[0m'
/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/reload_nginx.sh --category Stats --event RunAll --stage post --manual
/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/reload_nginx.sh --category Stats --event RunUser --stage post --manual
/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/accountcreate_hook_post.pl --category Whostmgr --event Accounts::Create --stage post --manual
/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/accountmodify_hook_pre.py --category Whostmgr --event Accounts::Modify --stage pre --manual
/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/accountmodify_hook_post.py --category Whostmgr --event Accounts::Modify --stage post --manual
/usr/local/cpanel/bin/manage_hooks delete script /opt/nDeploy/scripts/accountremove_hook_pre.py --category Whostmgr --event Accounts::Remove --stage pre --manual

/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/reload_nginx.sh --category Stats --event RunAll --stage post --manual
/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/reload_nginx.sh --category Stats --event RunUser --stage post --manual
/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/accountcreate_hook_post.pl --category Whostmgr --event Accounts::Create --stage post --manual
/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/accountmodify_hook_pre.py --category Whostmgr --event Accounts::Modify --stage pre --manual
/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/accountmodify_hook_post.py --category Whostmgr --event Accounts::Modify --stage post --manual
/usr/local/cpanel/bin/manage_hooks add script /opt/nDeploy/scripts/accountremove_hook_pre.py --category Whostmgr --event Accounts::Remove --stage pre --manual

[ ! -d /opt/nDeploy/domain-data ] && mkdir /opt/nDeploy/domain-data
[ ! -d /opt/nDeploy/user-data ] && mkdir /opt/nDeploy/user-data
[ ! -d /opt/fpmsockets ] && mkdir /opt/fpmsockets
[ ! -L /usr/local/cpanel/base/frontend/x3/nDeploy_cp ] && ln -s /opt/nDeploy/nDeploy_cp /usr/local/cpanel/base/frontend/x3/
[ ! -L /usr/local/cpanel/base/frontend/paper_lantern/nDeploy_cp ] && ln -s /opt/nDeploy/nDeploy_cp /usr/local/cpanel/base/frontend/paper_lantern/
[ ! -L /usr/local/cpanel/base/frontend/x3/apache_fpm_cp ] && ln -s /opt/nDeploy/apache_fpm_cp /usr/local/cpanel/base/frontend/x3/
[ ! -L /usr/local/cpanel/base/frontend/paper_lantern/apache_fpm_cp ] && ln -s /opt/nDeploy/apache_fpm_cp /usr/local/cpanel/base/frontend/paper_lantern/

echo -e '\e[93m Installing nDeploy plugin in cPanel \e[0m'
/usr/local/cpanel/scripts/install_plugin /opt/nDeploy/nDeploy_cp
/usr/local/cpanel/scripts/install_plugin /opt/nDeploy/nDeploy_cp --theme x3
echo -e '\e[93m Installing Apache_PHP-FPM plugin in cPanel \e[0m'
/usr/local/cpanel/scripts/install_plugin /opt/nDeploy/apache_fpm_cp
/usr/local/cpanel/scripts/install_plugin /opt/nDeploy/apache_fpm_cp --theme x3
