log_format abuser '$remote_addr - "$http_host" [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"';


# notes 
# https://blog.nginx.org/blog/rate-limiting-nginx
# github.com/limithit/ngx_dynamic_limit_req_module

dynamic_limit_req_zone $binary_remote_addr zone=limitreq5:10M rate=5r/s redis=127.0.0.5 block_second=300;
dynamic_limit_req_zone $binary_remote_addr zone=limitreq10:10M rate=10r/s redis=127.0.0.5 block_second=300;
dynamic_limit_req_zone $binary_remote_addr zone=limitreq20:10M rate=20r/s redis=127.0.0.5 block_second=300;
dynamic_limit_req_zone $binary_remote_addr zone=limitreq30:10M rate=30r/s redis=127.0.0.5 block_second=300;
dynamic_limit_req_redis port=6333;
dynamic_limit_req_status 418;


map $http_user_agent $bad_bot {
  "~SemrushBot/7.*" 1;
  "~YandexBot/3.0"  1;
  "~MJ12bot/v1.4.8" 1;
  "~GPTBot/1.4"     1;
  
  default 0;
}

